src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Districting_Status__c</fullName>
        <label>Districting Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TOM_ID__c</fullName>
        <label>TOM ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/Extension1Class.cls
Public class Extension1Class{

    public Extension1Class(ApexPages.StandardController controller) {

    }


public string AccountNameText{get;set;}
Public string Phone {get;set;}
public string Email{get;set;}
public string AddressText{get;set;}


public Extension1Class(String accname,string phn,string emailid,string addtext){
this.AccountNameText = accname;
this.phone = phn;
this.Email = emailid;
this.addressText = addtext;

}
public pagereference InsertData(){

Account acc = new Account();
acc.name = AccountNameText;
acc.Phone = phone;
acc.TOM_ID__c = email;
acc.Districting_Status__c = AddressText ;
insert acc;
return null;
}
}