src/objects/My_Offers__c.object
<CustomObject>
    <label>My Offers</label>
    <nameField>
        <label>My Offers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OM_SubOfferings__c.object
<CustomObject>
    <fields>
        <fullName>My_Offers__c</fullName>
        <label>My Offers</label>
        <referenceTo>My_Offers__c</referenceTo>
        <relationshipLabel>Subofferings</relationshipLabel>
        <relationshipName>Subofferings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OM_SubOfferings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OM_SubOfferings</label>
        <referenceTo>OM_SubOfferings__c</referenceTo>
        <relationshipLabel>Subofferings</relationshipLabel>
        <relationshipName>Subofferings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OM_SubOfferings</label>
    <nameField>
        <label>OM_SubOfferings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subofferings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExtJStabController.cls
public class ExtJStabController {

    public ExtJStabController(ApexPages.StandardSetController controller) {

    }public String selectedProductName;
      public String offer1 {get;set;}
    public String selectedoffertype;
    public String product1 {get;set;}
 
 ApexPages.StandardController controller;

Boolean disp2=false;
    Public Boolean getdisp2()
    {
    return disp2;
    }  
    


 
public List<OM_SubOfferings__c> myofr {
get {
if (myofr == null) {

myofr = [SELECT Name,id FROM OM_SubOfferings__c];
}
return myofr;

}
set;
}
 public pageReference productChange()
    {
selectedoffertype=[select o.name,o.My_Offers__r.name,o.id from OM_SubOfferings__c o where id=:offer1].Name;

 disp2=true;
        return null;
    }
    }